version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  backend:
    image: 8681463/foodgram_backend_arm64
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: 8681463/foodgram_frontend_arm64
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: 8681463/foodgram_gateway_arm64
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media