# Generated by Django 3.2.16 on 2025-02-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_unique_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hash',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Хэш шортлинки'),
        ),
    ]
