# Generated by Django 3.2.16 on 2025-02-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
