# Generated by Django 3.2.16 on 2025-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20250223_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload PNG or JPEG files', null=True, upload_to='images/recipes/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Up to 50 symbols', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Up to 200 symbols', max_length=200, verbose_name='Description'),
        ),
    ]
