# Generated by Django 3.2.16 on 2025-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='images/avatars/', verbose_name='Загрузить аватар'),
        ),
    ]
