# Generated by Django 3.2.16 on 2025-02-23 14:33

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_foodgramuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('username',), 'verbose_name': 'user', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('following__username',), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='Upload PNG or JPEG files', upload_to='images/avatars/', verbose_name='Upload profile picture'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(help_text='Up to 40 symbols', max_length=40, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(help_text='Up to 20 symbols', max_length=20, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.CharField(help_text='Up to 200 symbols', max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(help_text='Up to 30 symbols', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Follower'),
        ),
    ]
